import mysql.connector as mysql

# Conectamos a la base de datos
db = mysql.connect(
    host = "localhost",
    user = "root",
    passwd = "password",
    database = "turism"
)

cursor = db.cursor()

## Eliminamos la tabla de provincias si existe
query = "DROP TABLE IF EXISTS  `state`;"

## Ejecutamos la consulta
cursor.execute(query)

## Creamos la tabla de provincias
query = "CREATE TABLE `state` 
    ( `id` int NOT NULL AUTO_INCREMENT, 
    `name` varchar(100) NOT NULL, 
    `description` longtext, 
    `image_url` varchar(255) DEFAULT NULL, 
    `video_url` varchar(255) DEFAULT NULL, 
    PRIMARY KEY (`id`), 
    UNIQUE KEY `name_UNIQUE` (`name`), 
    UNIQUE KEY `video_url_UNIQUE` (`video_url`), 
    UNIQUE KEY `image_url_UNIQUE` (`image_url`)
    );"

## Ejecutamos la consulta
cursor.execute(query)

## defining the Query
query = "INSERT INTO `turism`.`state` (`name`, `description`, `image_url`, `video_url`) VALUES (%s, %s, %s, %s);"
## storing values in a variable
values = [
    (
        "Mendoza", 
        "Los encantos del turismo en Mendoza pueden ser disfrutados durante todo el año: sus bellezas naturales y la inmensidad de sus montañas, la fama de sus bodegas y sus excelentes vinos, y la conocida Fiesta de la Vendimia que se celebra cada mes de marzo. Gracias al desarrollo y expansión del sector vitivinícola a nivel internacional, las bodegas más importantes abren las puertas de sus establecimientos a jerarquizados wine-tours. La idea es mostrar al público la rutina diaria necesaria para elaborar sus mejores productos, entre ellos el famoso malbec. Cualquiera sea el punto cardinal elegido, Mendoza lo tiene todo. Al norte, el circuito de alta montaña invita a encontrarse con el mítico cerro Aconcagua y con todos los caminos y recovecos que conducen hacia la cumbre más alta del continente americano. Al sur, las pujantes y siempre nuevas ciudades de San Rafael y Malargüe convocan a toda la familia con sus actividades recreativas y deportes de aventura en escenarios naturales como ríos y embalses, que fueron poblados en los últimos años por cabañas y hospedajes para todos los gustos. En la ciudad de Mendoza y sus alrededores, regiones como Luján de Cuyo, Maipú y Chacras de Coria conforman un aglomerado turístico a minutos del casco urbano. Un poco más alejados, las zonas de Potrerillos y el Valle de Uco también ofrecen varias alternativas de excursión. Junto con el circuito Sanmartiniano, muestran al visitante que, además de buen vino, esta provincia de la Argentina posee una historia rica y una cultura fascinante que se manifiesta también en el presente.",
        "https://naturalmerchants.com/organicwines/wp-content/uploads/2017/07/Chakana_background.jpg",
        "https://www.youtube.com/watch?v=pSFfq7A_FQg"
    ),
    (
        "Buenos Aires", 
        "La Provincia de Buenos Aires, una de las más ricas de la Argentina, encierra paisajes muy diferentes entre sí, como el campo, las sierras, las grandes urbes, las lagunas, el delta del Paraná y, por supuesto, todo el abanico de playas que se extiende por la costa atlántica. Es ideal para el turismo. Ciudades como La Plata, Mar del Plata, Tres Arroyos, Azul, Trenque Lauquen, Luján, Belén de Escobar o la sureña Bahía Blanca, todas poseen los atractivos comunes a las grandes urbes, y pequeños espacios propios que las distinguen. En la región serrana, los sistemas de Ventania y Tandilia albergan hermosas localidades que atraen al visitante en cualquier época del año. Sierra de la Ventana, Villa Ventana, Tornquist, Saldungaray, Tandil, Balcarce o Sierra de los Padres gozan de esta privilegiada geografía y microclima. En cuanto al campo, la provincia de Buenos Aires posee las típicas características de lo que se denomina campo argentino, donde además de las plantaciones agrícolas puede divisarse el ganado vacuno, origen del famoso asado argentino. Entre las ciudades de este ámbito existen algunas que desde hace tiempo abrieron las puertas al turismo: San Antonio de Areco y Mercedes son sólo dos de las más conocidas. Para los que prefieren armonizar un día de campo con la cercanía del agua, lo ideal es conocer la región de las lagunas. Cercanas a la Capital Federal, las encadenadas de Chascomús, San Miguel del Monte, Lobos o Navarro son las que atraen turistas en todas las temporadas, ya sea para dedicarse a la pesca del pejerrey en invierno, como para practicar deportes acuáticos con la llegada del calor. El delta del Paraná es otra de las regiones que convocan muchos visitantes. Se accede desde la ciudad de Tigre, donde se encuentra la estación fluvial que nos permite adentrarnos en un mundo interminable de islas, ríos y pequeños arroyos donde el hombre ha instalado sus casas y aprendió a vivir hermanado con la naturaleza. La región de las playas, que va desde la ciudad de San Clemente del Tuyú hasta la de Carmen de Patagones e incluye entre muchas otras a las famosas Pinamar, Villa Gesell y Mar del Plata, son el destino perfecto para millones de visitantes cada verano. Arenas limpias, agua fresca y mucha gente, un trío imperdible que se repite en cada una de las localidades que miran al océano Atlántico. Por todo esto, la provincia de Buenos Aires es uno de los destinos preferidos al emprender un viaje.", 
        "https://images8.alphacoders.com/841/thumb-1920-841065.jpg", 
        "https://www.youtube.com/watch?v=F2sepCUnENg"
    ),
    (
        "Chaco", 
        "La capital de Chaco, Resistencia, es conocida como la ciudad de las esculturas por poseer más de un centenar de figuras al aire libre que son el orgullo de sus pobladores y punto de encuentro de sus vecinos. La Bienal Internacional de Esculturas en Resistencia convoca a los más importantes artistas y escultores de la Argentina y edición tras edición logra récords de incondicionales seguidores. Por otra parte tenemos el puente General Manuel Belgrano que une Resistencia con la cercana capital correntina, ubicada del otro lado del río Paraná y a pocos kilómetros de la desembocadura del río Paraguay. Para los pescadores deportivos, la Fiesta Nacional de Pesca del Dorado en la Isla del Cerrito es uno de los eventos más importantes del año, y campo adentro se festeja la Fiesta Nacional del Algodón en Presidente Roque Sáenz Peña, la ciudad termal de la provincia. El Parque Nacional Chaco fue creado en 1954 y desde su surgimiento intenta preservar la flora y fauna local. En el lugar todavía podemos encontrar jaguares, que son los mayores félidos de América y los terceros en el mundo, después del tigre y el león.", 
        "https://desinformemonos.org/wp-content/uploads/2018/02/80212-Chaco-Province.jpg", 
        "https://www.youtube.com/watch?v=6a1eV4SQYgA"
    ),
    (
        "Tierra del Fuego", 
        "El turismo en la provincia constituye uno de los potenciales de mayor relevancia. En la ciudad de Río Grande, hay mesetas y llanuras con vegetación escasa de coirones, guanacos, zorros y varias estancias con cría de ganado ovino y vacuno, que en verano les abren sus puertas a los turistas interesados en hacer vida de campo.Hacia el sur, hay un sector de montañas de baja altura que forman parte de la cordillera de los Andes, con bosques y arroyos, y donde, en la costa marítima del canal de Beagle. En la capital, Ushuaia, el visitante puede tomar un city tour para ver lo que hasta mediados del siglo XX fue la Cárcel del Fin del mundo. Hacia el oeste de Ushuaia, camino al Parque Nacional Tierra del Fuego, se puede tomar el Tren del Fin del Mundo, que ya dentro del parque combina con un bus que recorre la reserva natural entre turbales, lagunas y diques de castores, animal de filosos dientes y gran destructor de bosques, que el gobierno ha decidido comenzar a eliminar. Entre las montañas que rodean la ciudad se destaca en el noroeste el glaciar Martial, un lugar ideal para realizar en verano diferentes actividades, como trekking o caminatas, que pueden variar desde recorridos de pocos minutos a itinerarios de medio día o un día entero, con distintos niveles de dificultad.", 
        "https://www.cadena3.com/admin/playerswf/fotos/ARCHI_642682.jpg", 
        "https://www.youtube.com/watch?v=8ktGScHJqKc"
    ),
    (
        "Misiones", 
        "Naturaleza privilegiada y destinos culturales e históricos se conjugan para que muchos decidan conocer esta famosa provincia. Su tierra colorada, imponentes saltos de agua e impenetrable selva son su mejor carta de presentación ante el mundo. El sitio más emblemático son las Cataratas del Iguazú ubicadas dentro del Parque Nacional Iguazú, es un monumento natural que no puedes dejar de conocer al ser una de las 7 maravillas del mundo. En total tienen 275 saltos de hasta 70 metros de altura, son un verdadero espectáculo que te impresionará. Al adentrarte en ellas por sus pasarelas mimetizadas vivirás la experiencia de estar en plena selva. Así avistarás muy cerca estas caídas de agua y conocerás la Garganta del Diablo, el pico más alto. En Misiones también puedes conocer las Reducciones Jesuíticas. La de San Ignacio es la más conservada y recibe al año miles de visitantes. Por último tenemos la Ruta del Té que es una actividad que se realiza la segunda quincena de noviembre en el que se disfruta de grandes ofertas gastronómicas.", 
        "https://static.misionesonline.news/wp-content/uploads/2019/05/77f7f04071a1b55518ad3b767d4bc747-1run935d5go0-552tdsu56mv0.jpg", 
        "https://www.youtube.com/watch?v=RiRQiozXFGA"
    ),
    (
        "Tucumán", 
        "La topografía de Tucumán es de las más variadas de la región suramericana.  Cuenta con casi toda la gama de paisajes posibles como imponentes montañas, deprimidas llanuras, selvas, bosques y desiertos. En todos los casos tendrás opciones para el disfrute y el descanso con un gran contenido histórico y arqueológico. A solo 26 kilómetros de la capital encontraremos el Dique El Cadillal, donde se pueden realizar actividades como kayak, mountain bike, windsurf, pesca, caminata y mucho más. El clima en el Dique El Caldillal es único: no es frío ni caluroso, sino agradable y ameno. Así que adentrarte en sus aguas no será un problema. Uno de los paseos mas importantes de la provincia es el Circuito Ciudad Histórica, donde se pueden observar las calles que vieron nacer la independencia del país y se conocen los edificios cívicos mas importantes de su historia como la Casa Histórica, la Plaza Independencia, ademas de galerías y museos de arte, y varias iglesias autóctonas. Por ultimo, se puede destacar la Ruta del Vino, donde se puede dar el lujo de conocer una de las zonas de producción de vinos mas altas del mundo.", 
        "https://buenavibra.es/wp-content/uploads/2018/10/Webp.net-resizeimage-9.jpg", 
        "https://www.youtube.com/watch?v=tpV4K16KY6s"
    ),
    (
        "Entre Ríos",
        "Pensar en el turismo en Entre Ríos nos remite en forma inmediata a las bondades del Litoral de la Argentina, a los colores de sus carnavales, a los tamaños espectaculares de sus peces (entre los que sobresale el dorado y el surubí), a sus termas benefactoras, a sus playas repletas de visitantes durante el verano. Es que decir Entre Ríos es entender que esta tierra prodigiosamente verde que se halla entre las márgenes de los principales ríos de la Argentina, el Paraná y el Uruguay, es el escenario ideal para realizar actividades recreativas todo el año, y que también posee un importante bagaje cultural e histórico propio como para que en ella exista todo lo que el visitante quiera encontrar. Pesca, playas, carnavales y, más recientemente, termas, son los productos temáticos que han ayudado a que el turismo en Entre Ríos sea la opción elegida a la hora de planificar un viaje de descanso o diversión, un fin de semana largo, un feriado o las clásicas vacaciones de invierno y de verano. Ciudades como Gualeguaychú con sus Carnavales y con la belleza de sus playas, La Paz con sus islas serpenteantes y sus gigantes dorados, Colón con su Parque Nacional El Palmar y la exuberancia y capricho de sus millares de palmeras, pueblos-ciudades mansas como Chajarí, Federación, Villa Elisa y Victoria invitan a prolongar la estadía gracias al relax que brindan sus termas y a la tranquilidad y seguridad de sus días y noches. Paraná, capital de la provincia que hizo punta con el slogan de Todos tus verdes y hoy sin dudas se ha transformado en La provincia más Termal de Argentina, posee los encantos de una gran urbe armonizados con la hora de la siesta y con las costumbres de un pueblo chico, con su vuelta del perro, con sus modismos y con sus horarios. La moderna Concordia deslumbra con su paso a Uruguay y la Represa de Salto Grande, su lago que pronto tendrá orillas termales y su zona para pescar los dorados más grandes del mundo con devolución obligatoria. La histórica Concepción del Uruguay junto a Gualeguay fueron bautizadas como las históricas y hoy han encontrado nuevos atractivos turísticos como la pesca y las termas para seguir convocando al visitante.", 
        "https://dpn03q9flmgew.cloudfront.net/07-05-2018/t_1530820067596_name__VIVI_ARGENTINA___ENTRE_RIOS___EL_PALMAR.jpg", 
        "https://www.youtube.com/watch?v=1usVwJKpgq8"
    ),
    (
        "La Pampa",
        "La Pampa es privilegiada por la naturaleza, la variedad de la flora y fauna y sus hermosos paisajes son ideales para el turismo ecológico y alternativo, las huellas de la cultura indígena han sido rescatadas y nos permiten conectarnos con el pasado en un ambiente único. Debemos resaltar la calidad de la cocina que ofrecen en los restaurantes, los Hoteles ofrecen opciones para todos los presupuestos. Visitando los alrededores de la ciudad de Jacinto Arauz, se puede experimentar la transición desde un relieve de llanura a uno de mesetas, descubriendo entre tanto magníficas lagunas. Tal vez la más conocida sea La Colorada Chica. Emplazada a tan sólo 30 kilómetros al sur de Jacinto Arauz, esta mina de sal impacta por su extraña coloración roja producto de una infinidad de pequeños crustáceos que producen el llamativo efecto visual. Un circuito paisajístico y educativo que ningún visitante de esta zona de La Pampa puede omitir en su itinerario. Única en el mundo, la Reserva Natural Parque Luro protege en su extensión un bosque de caldenes, además de otras especies de flora y una riquísima avifauna. Cuenta con tres senderos peatonales -Sendero de la Laguna, Sendero del Bosque y Sendero del Médano- que permiten a los visitantes la contemplación y comprensión de los ambientes naturales. Completas instalaciones con áreas de camping, fogones, parrillas, juegos para niños, locales gastronómicos, proveeduría y piscina, perfeccionan la oferta turística de este parque que se encuentra a 35Kms. de la capital de la provincia. Conocer la vida de campo desde la propia vivencia es una de las opciones más interesantes de Santa Rosa. En medio de un paisaje magnífico que descubre el amanecer y se oculta con el sol, muchos establecimientos rurales pampeanos ofrecen a los turistas la posibilidad de alojarse en sus cascos, saborear platos típicos, entrar en contacto con la peonada y participar de las labores diarias y las costumbres del lugar. Por ultimo podemos destacar el Parque Nacional Lihué Calel, entre sus recursos naturales se destacan las serranías, cuya altura máxima alcanza los 600 metros sobre el nivel del mar; el monte dominante; las especies de flora que crecen en los roquedales; y las múltiples especies animales. El parque ademas cuenta con instalaciones para acampar, y personal capacitado, incorporan comodidad a este maravilloso atractivo de La Pampa que no podrá dejar de visitar.", 
        "https://d14aol1otb1k4s.cloudfront.net/r/les-images-main/1020x1020/dcfb39b2de061fb8ebd39c7bf33780408afc08e36ccdc1387c8fd7fdc71dd2f9.jpeg/webp", 
        "https://www.youtube.com/watch?v=70Gwko4j8WE"
    ),
    (
        "Córdoba",
        "El turismo en Córdoba ofrece al visitante innumerables atractivos, enmarcados por los distintos sistemas serranos del oeste y noroeste provincial. Sus ríos y arroyos, sus interminables áreas verdes y boscosas, las bondades del clima y los paisajes naturales únicos, atraen visitantes todo el año hacia este privilegiado lugar del mundo. Tradicional y moderna, cultural e histórica por donde se la mire, donde el legado español y jesuita se exhibe a través de sus estancias e iglesias, Córdoba posee una de las plazas hoteleras más importantes del país, junto a una infraestructura de servicios y prestadores expertos que satisfacen las demandas recreativas, de aventura, gastronómicas y de espectáculos de quienes se acercan a disfrutar las distintas opciones que ya son clásicas de esta provincia mediterránea de la Argentina. Igual de cautivantes son sus ciudades, que ofrecen distintas alternativas y nuevas experiencias. Comenzando, por supuesto, por Córdoba Capital, la ciudad homónima de la provincia y su centro político, donde a diario se respira la idiosincrasia y la filosofía del pueblo cordobés. Villa Carlos Paz es el imán del verano y uno de los principales centros receptivos del país durante toda la temporada estival, no sólo debido a sus increíbles atractivos naturales sino también a la gran cantidad de espectáculos teatrales que allí se ofrecen. Cada mes de octubre, la mirada de los visitantes se posa en Villa General Belgrano, cuya Fiesta Nacional de la Cerveza atrae a entusiastas de toda la Argentina y del mundo. En la muy cordobesa ciudad de Cosquín, capital nacional del folklore, se destaca precisamente su festival de música y bailes típicos de nuestra tradición, pero también el más reciente festival Cosquín Rock. Córdoba posee caminos deslumbrantes que atraviesan los distintos sistemas de sierras, como las famosas Sierras Chicas, las Sierras Grandes, Traslasierra y el Camino de las Altas Cumbres. Los fanáticos de los fenómenos paranormales tienen su espacio convocante en el Cerro Uritorco, cercano a Capilla del Monte, famosa por sus rarezas y por tener la primera calle techada del país. Diques y embalses, atractivos naturales e histórico-culturales, a lo que se suman un clima prodigioso, hacen de la provincia de Córdoba una de las más significativos a nivel turístico. Quizás porque lo tiene todo, y porque día a día sorprende con algo nuevo por descubrir en sus interminables rincones.", 
        "https://blog.bestday.com.ar/wp-content/uploads/2018/01/cba.jpg", 
        "https://www.youtube.com/watch?v=1djLG2ZDFm4"
    ),
    (
        "Santa Cruz",
        "La provincia de Santa Cruz se ha transformado en protagonista de las guías de turismo a pesar de encontrarse en el lejano sur, y tiene tanto que ofrecer que es válido pensar en ella para unas vacaciones. Ocupa una gran superficie y brinda gran cantidad de recursos turísticos y paisajes deslumbrantes. Su vasta geografía muestra distintos tipos de suelos, climas muy diferenciados, temperaturas bajas siempre y una gran amplitud térmica. Sobre el sector oeste del territorio, donde se despliega la Cordillera de los Andes, una sucesión de lagos ocupa el área cercana al límite con Chile e incluso algunos son compartidos con el vecino país. Las ciudades de Perito Moreno y Los Antiguos se destacan por su vida en relación a los espejos lacustres, en los cuales la pesca deportiva es una de las actividades más atractivas. A su vez, en la zona de Gobernador Gregores se ha fortalecido el turismo de estancias, donde se muestran las tareas propias de la cría de ovinos pero también se ofrecen salidas de pesca y aventura por los alrededores. Hablar de glaciares es imaginar uno de los monumentos naturales más extraordinarios que el hombre puede contemplar. Sobre la cordillera se despliega el Parque Nacional Los Glaciares y la ciudad de El Calafate es la puerta de acceso a sus campos de hielo milenarios que se han erigido en un destino mundial por su espectacularidad; cuenta con hotelería y gastronomía de primer nivel. A pocos kilómetros de allí, El Chaltén, un pueblo pequeño al pie del monte Fitz Roy, ha logrado gran difusión por haber sido nombrado Capital Nacional del Trekking. En la costa del océano Atlántico, desde Caleta Olivia hasta Río Gallegos, se asientan varios puertos comerciales que en el pasado fueron salida obligada del petróleo y el ganado de la zona; hoy son receptores de turismo. Sus golfos, acantilados y playas amplias de arena y pedregullo invitan a caminar y a dedicarse a la pesca de mar. Deseado, San Julián y Santa Cruz miran hacia el horizonte marino y son visitados por los amantes de los parajes vírgenes.", 
        "https://media2.trover.com/T/5c40b872a10dc942bf00777b/fixedw_large_4x.jpg", 
        "https://www.youtube.com/watch?v=mqYL0iQitYs"
    ),
    (
        "Santa Fe",
        "La Provincia de Santa Fe conjuga de manera armónica dos geografías típicas de la Argentina: el Campo y el Litoral. Conocida mundialmente por sus valores ganaderos y agropecuarios, a los que se suma la riqueza del interminable río Paraná y de las grandes ciudades que se edifican en su ribera, Santa Fe posee todo lo que el turista necesita para disfrutar de una memorable estadía cultural y recreativa. Alojamientos y restaurantes de primer nivel, tanto en Santa Fe capital como en Rosario, atractivos naturales, paseos únicos y sitios históricos a lo largo de todo su territorio hacen de esta provincia un destino imperdible para conocerlo en algún momento, cualquiera sea la excusa. Con su propia receta de alfajores y cerveza, y reconocida en todo el país por las costumbres, valores e idiosincrasia de sus habitantes, Santa Fe logra enamorar a quien la visita por primera vez. Conocida también como la provincia de la bota o de la pierna, basta con mirar un mapa de ella para ver como se entrelaza con las provincias limítrofes, proponiendo distintas geografías. Con Córdoba y Santiago del Estero al oeste, Buenos Aires al sur, Entre Ríos y Corrientes al este y Chaco al norte, Santa Fe ofrece diversión cualquiera sea el punto cardinal elegido por los visitantes, o el de la procedencia de éstos.", 
        "https://descubrirturismo.com/wp-content/uploads/2017/03/Santa-Fe-d%C3%ADa.jpg", 
        "https://www.youtube.com/watch?v=IZI5MtkBt_E"
    ),
    (
        "Salta",
        "La provincia de Salta posee un clima benigno y los encantos indicados para ser una de las más visitadas por los turistas durante todo el año. A sus bellezas naturales, que se pueden apreciar en las distintas regiones que alberga, se suma la diversidad de sus habitantes, que encandila a quienes se acerquen hasta allí por sus tradiciones y costumbres, algunas seculares. Salta Capital es ideal para alojarse en ella y disfrutarla desde el mismo momento en que salimos del hotel y comenzamos a caminarla. Museos, iglesias, edificios históricos, plazas con sus cafés y paseos varios nos permiten ver la influencia colonial, que se aprecia en la arquitectura y en uno de los cascos históricos más protegidos de Argentina. Aquí sin dudas, el pasado se preserva. Al oeste, la Cordillera de los Andes y la Puna, con su increíble viaducto La Polvorilla y el Tren de las Nubes. Al sur, los Valles Calchaquíes. Al norte, el Chaco Salteño, cuyos verdes interminables la asemejan a la mismísima selva misionera. Única en paisajes, a cada sitio inigualable se suma su excelencia gastronómica que se manifiesta en sabores, colores y aromas propios de esta región del mundo. Aquí el comino es oro y tal es la bondad de los salteños que locros, tamales y empanadas tienen parte de este bello tesoro. Desde la ciudad de Salta hacia el resto de la provincia las opciones también son paradisíacas: destinos cercanos como Cachi y Cafayate, o más lejanos como las Salinas Grandes y el camino hasta ellas, son excursiones conocidas ya mundialmente, y con los méritos suficientes para prolongar la estadía del turista por varios días más.", 
        "https://magazine-wellness.com/wp-content/uploads/2019/02/%C2%A1Los-atractivos-paisajes-de-Salta-la-linda.jpg", 
        "https://www.youtube.com/watch?v=mrzSxGWAKy4"
    ),
    (
        "Corrientes",
        "La provincia de Corrientes integra la región del Litoral, que goza de temperaturas elevadas todo el año. Sus famosos ríos, sus esteros y los yacarés, la pujanza de su gente y sus tradiciones musicales hacen de Corrientes una de las provincias más singulares de la Argentina. El chamamé es la música tradicional de los correntinos, y en ella descansa la filosofía de vida de sus pobladores. La religiosidad de éstos se manifiesta también en procesiones y encuentros tradicionales que se mantienen vivos a lo largo de toda la provincia. Entre los atractivos de Corrientes figuran los balnearios de los ríos Paraná y Uruguay, las catedrales e iglesias centenarias en el centro de sus ciudades, el enorme humedal conformado por los mundialmente famosos Esteros del Iberá; y toda la belleza de su homónima Capital, en donde la cultura se manifiesta a través de sus museos y de varias instituciones y edificios públicos cuyo estilo arquitectónico atesora reliquias de incalculable valor histórico y religioso. El dorado y el surubí le han aportado a sus ríos el color necesario para que todos los años, en Paso de la Patria y en Goya, tengan lugar las dos Fiestas Nacionales de pesca más importantes del país. Además de ser otro pesquero importante, la ciudad de Esquina es una de las más atractivas para los amantes de la fotografía paisajística y de la ornitología en general. Corrientes tiene payé reza el dicho, y es cierto. Basta con conocerla para enamorarse perdidamente de ella y para que su efecto de amuleto o imán nos atraiga siempre.", 
        "https://media-cdn.tripadvisor.com/media/photo-m/1280/18/99/79/33/costanera-de-corrientes.jpg", 
        "https://www.youtube.com/watch?v=rZCF2T7pGrg"
    ),
    (
        "Rio Negro",
        "La provincia de Río Negro ocupa un amplio corredor del sur del país, entre la Cordillera de los Andes al oeste y las costas del Océano Atlántico en el este. Ambas geografías, tan distintas, son las más reconocidas por contar con centros turísticos de mucha relevancia. El área cordillera tiene una zona lacustre enmarcada en montañas y bosques de especies nativas de gran espectacularidad escénica. San Carlos de Bariloche es la ciudad estrella por su posición en la zona andina pero también por la visión de sus primeros pobladores, que convirtieron su pueblo en un centro turístico de excelencia. Tanto en verano como en invierno, las actividades de turismo no disminuyen. Cada una de ellas tiene sus adeptos, de distintas edades y condiciones sociales. Se suman las fiestas populares que le dan brillo, como la de la nieve, la del chocolate, la del curanto, la de las colectividades, la Semana de la Aventura y otras. La costa rionegrina junto al atlántico cobra vida cada verano cuando el sol llama a acercarse a sus playas inmensas junto a las prácticas náuticas y de pesca. En ellas se suceden pequeños balnearios que ven aumentado el número de visitantes cada año, quienes resultan atraídos por las aguas cálidas que baña el litoral. Se destaca especialmente Las Grutas por sus características propias y por la red vial conectiva. Al norte, la provincia tiene como límites naturales los ríos Limay, Neuquén y Colorado. Este último corre paralelo al Río Negro por la zona de los valles (alto, medio e inferior), un área de gran importancia para la economía local ya que sus productos frutícolas se exportan al mundo. Por último, la contrastante región central de la estepa es interesante por sus cañadones entre volcanes y sierras, arroyos y lagunas temporarias, en la cual se destaca su patrimonio paleontológíco y arqueológico.", 
        "https://media.lmcipolletti.com/adjuntos/195/imagenes/003/604/0003604155.jpg", 
        "https://www.youtube.com/watch?v=wUZmHs-BQC4"
    ),
    (
        "Neuquén",
        "Los atractivos para el turismo que la provincia de Neuquén muestra a lo largo y a lo ancho de su territorio son múltiples y cada región tiene su característica particular. La zona de la estepa, con centro en la propia capital Neuquén, ofrece un tipo de actividad turística basado en la paleontología, con varias excavaciones y museos, y la más reciente Ruta del Vino, que congrega distintas bodegas que abren sus puertas a los visitantes. En el norte, las poblaciones antiguas como Chos Malal y Andacollo, dedicadas a la cría de chivos y ovejas, guardan las tradiciones del Neuquén rural. En esta zona, ya más al sur y sobre la cordillera, se destaca la región termal, con eje en las localidades de Caviahue y Copahue. En la región oeste central, en Aluminé y Villa Pehuenia, se destacan los milenarios bosques de araucarias que forman parte de una geografía agreste y seca. Al sur, la zona de los lagos es admirada por sus bosques y sus intrincadas cuencas, cuyas aguas cristalinas bañan tierras de origen volcánico. La Ruta de los 7 Lagos se desarrolla en este sector y es una muestra de la armonía natural de la región, uniendo San Martín de los Andes con Villa la Angostura. Las actividades de aventura tienen cabida en varios sectores. El ascenso a volcanes como el Lanín y el Domuyo para expertos, los trekking de larga distancia a los que invita la Huella Andina, o los más livianos que se practican en cada uno de los destinos, son sólo ejemplos. Quizás el deporte más destacado sea la pesca y, en especial, la modalidad con mosca. Los inviernos con sus fuertes nevadas dan origen a cinco centros de esquí a lo largo del cordón montañoso neuquino: Chapelco, Cerro Bayo, Caviahue, Batea Mahuida y Primeros Pinos, atraen a los amantes de los deportes sobre nieve. Neuquén, tierra generosa para los que un día llegaron a poblarla, hoy lo sigue siendo con quienes la visitan simplemente para descansar y distraerse.", 
        "https://www.sanmartinadiario.com.ar/fotos/14777_16538.jpg", 
        "https://www.youtube.com/watch?v=oUGHOzMR2SQ"
    ),
    (
        "San Luis",
        "La provincia de San Luis posee una geografía perfecta para el turismo, y no sólo para mirarla sino también para disfrutar de distintas actividades recreativas y de aventura que se han multiplicado en las últimas décadas. A lo largo de su límite noreste encontramos una innumerable cantidad de poblaciones y pequeñas urbes que han hecho de las serranías su lugar en el mundo. Aquí, las sierras de los Comechingones y la región conocida como Valle de Conlara forman el escenario ideal para que la ciudad de Merlo sea uno de los destinos más visitados de la Argentina cualquiera sea la época de año elegida. En sus alrededores se suceden distintos pueblitos que cuentan en su mayoría con cabañas para alquilar y disfrutar así de los encantos de la sierras puntanas. Carpintería, es uno de ellos. Allí se practica el parapente y el aladeltismo, y por eso se bautizó al lugar como la Capital Nacional del Vuelo Libre, En el centro de la provincia se encuentra la capital San Luis, y allí coexisten sierras, diques, termas y salinas, haciendo de los alrededores de la ciudad una diversidad de paisajes increíbles, destacándose sitios como El Trapiche, la Villa del Dique La Florida, Potrero de los Funes con su singular autódromo, La Carolina y su vieja mina de oro y otros lugares de valor histórico como Inti Huasi que merecen un alto durante un viaje. Al oeste, el relieve vuelve a ascender y aparece un cordón montañoso bautizado como Sierra de las Quijadas con Parque Nacional homónimo. Allí, la belleza del paisaje y la tranquilidad que brinda la altura logran que el cóndor se sienta a sus anchas y vuele libre sin preocupación alguna por ser observado por los turistas que se acercan a avistarlos. La provincia presenta al sur una serie de lagunas y llanos que la asemejan a otras áreas del país, ricas en salitres pero también en flora y fauna, una zona bien húmeda dónde todo crece. Histórica y tradicional, la ciudad de Villa Mercedes, con su famosa Calle Angosta, es la puerta de entrada a otro sector de la provincia puntana que también merece conocerse.", 
        "https://horadeopinion.com.ar/wp-content/uploads/2018/12/potrero9.jpg", 
        "https://www.youtube.com/watch?v=6JDA-Hrif6o"
    ),
    (
        "Chubut",
        "La provincia de Chubut encierra dos paisajes opuestos muy buscados por el turista que proviene de las grandes ciudades: la montaña y el mar. Y una interminable variedad de atractivos turísticos. Las ciudades importantes sobre la costa del océano, como Rawson,Puerto Pirámides y Puerto Madryn, donde se pueden avistar ballenas francas, en la Península Valdés, se vinculan con la zona cordillerana mediante excelentes rutas y caminos patagónicos. Así puede arribarse a las localidades de esta región: Esquel, Lago Puelo o Trevelin, entre otras. El centro de la provincia alberga la región de mayor tamaño, que se conoce como Meseta Central. En ella aparecen destacados atractivos como Los Altares, el bosque petrificado del dique Ameghino y el área protegida Piedra Parada, una formación rocosa de 200 metros de altura y 150 metros de diámetro, totalmente sola en la inmensidad de la planicie. El sur de la provincia es otra de las regiones turísticas más desarrolladas, con atractivos como el Parque Marino Costero, al que puede llegarse desde Camarones o Comodoro Rivadavia, la práctica del carrovelismo en Rada Tilly y el bosque petrificado José Ormaechea, al que se accede desde la ciudad de Sarmiento, y la Fiesta de la Esquila en Río Mayo. Además existen excelentes puntos para la pesca deportiva de truchas y salmones, difundida en el alto río Senguer y río Pico. Todo esto convierte a Chubut es una excelente alternativa a la hora de programar un viaje por la Patagonia.", 
        "https://patagonia.net/wp-content/uploads/2019/04/Madryn-1-1024x685.jpg", 
        "https://www.youtube.com/watch?v=0WIoUc06vpU"
    ),
    (
        "Jujuy",
        "La provincia de Jujuy se encuentra en el extremo norte de Argentina y sus condiciones geográficas la hacen un lugar muy especial, algo que el turismo descubrió en las últimas décadas incorporando hasta las pequeñas ciudades jujeñas entre los destinos más elegidos a la hora de emprender un viaje hacia esta región. Tilcara, Purmamarca, Maimará y Humahuaca son algunas de las poblaciones más visitadas y celebran distintos eventos que cada año convocan a miles de turistas atraídos por las comidas típicas, las fiestas populares y los carnavales más originales del mundo. La Quebrada de Humahuaca es Patrimonio Natural y Cultural de la Humanidad declarado por la UNESCO. En ella se encuentran diseminados pequeños pueblitos cuyas geografías de por sí merecen una estadía. La capital jujeña también logra enamorar a quién la conoce por primera vez. Sus quebradas y valles, la amabilidad de su gente y los rincones más impensados de esta ciudad logran hacerla distinta, para que todos quieran volver. Otro lugar imperdible de Jujuy son las Salinas Grandes, perfecto paisaje para hacernos creer que nos encontramos en un planeta distinto, o dentro de un cuento de ciencia ficción. Allí todo es blanco sal y, cuando llueve, las grietas del piso desaparecen y todo se transforma en un infinito espejo que refleja cada cosa que hacemos. Un lugar único.", 
        "https://www.diariopanorama.com/fotos/notas/2019/06/06/322270_20190606104137.jpg", 
        "https://www.youtube.com/watch?v=NJZ8y6UeLkI"
    ),
    (
        "San Juan",
        "La provincia de San Juan posee paisajes increíbles que favorecen al turismo, y entre ellos se destaca como destino el Parque Provincial Ischigualasto, popularmente conocido como Valle de la Luna. Éste exhibe una geografía pocas veces vista, dónde las formaciones orográficas toman apariencias insólitas, pasando por todas las escalas de grises y ocres. Cuna de buenos y reconocidos vinos, a lo largo de toda San Juan se han desarrollado innumerable cantidad de bodegas que, junto a las de su hermana provincia de Mendoza, forman parte de la región conocida como Cuyo y se encargan de proveer esta bebida a todos los puntos de Argentina. Durante el mes de febrero San Juan celebra la Fiesta Nacional del Sol, dónde se rinde culto a todos los que participan en el proceso del vino, pioneros y bodegueros, finalizando con la famosa Vendimia y una fiesta popular seguida por todos los sanjuaninos. Tanto la ciudad capital como la mayoría de sus pequeños centros urbanos, gozan de una fisonomía parecida, en la que se destaca una arquitectura que es colonial y moderna al mismo tiempo, con calles y avenidas amplias, y con distintos espacios públicos donde la vegetación y los árboles son protagonistas. Los innumerables paisajes de San Juan y sus exquisitos rincones geográficos no sólo atraen a los turistas, sino que también consiguen que los locales viajen por toda la provincia cada fin de semana largo en busca de paz y descanso, lo que ha provocado en los últimos años un crecimiento en la oferta de alojamiento alrededor de todos los embalses y espejos de agua naturales que posee esta bella región.", 
        "https://cdn.thecrazytourist.com/wp-content/uploads/2018/01/Valle-de-la-Luna.jpg", 
        "https://www.youtube.com/watch?v=y7ud0NOFhoE"
    ),
    (
        "Formosa",
        "Formosa está situada en el norte argentino y limita al oeste con la provincia de Salta y al sur con la del Chaco. Su geografía rica en ríos, lagunas y bañados la hacen una de las más húmedas del país, albergando una gran variedad de especies de flora y fauna. El origen de su nombre está ligado a una vuelta del río Paraguay que los conquistadores españoles llamaron Vuelta Fermosa (hermosa, en castellano antiguo). Aquí se ubicó una reducción jesuítica hacia el año 1673, poblada por los misioneros y pueblos guaraníes originarios de la zona. Rodeada por los ríos Pilcomayo, Paraguay y Bermejo, su territorio permanece en gran parte inexplorado y hoy abre sus puertas al turismo de aventura y al contemplativo, con bellos paisajes en su máxima pureza que son vividos y disfrutados por el visitante. Entre los atractivos de la provincia se encuentran la Reserva Natural Guaycolec, la Isla de Oro y el Parque Botánico Forestal Tortorelli. Clorinda, Las Lomitas, Comandante Fontana y Espinillo son las ciudades más importantes de la provincia, además de la capital formoseña que atrae también por su arquitectura y en la cual se destacan la Casa de Gobierno, la fachada de la Iglesia Catedral Nuestra Señora del Carmen, su nueva Costanera y los balnearios sobre el río Paraguay. Anualmente se realizan la Fiesta de la Corvina de Río, el Encuentro de Pueblos Originarios de América y la Fiesta del Pomelo, tres festividades que reciben a visitantes de todo el país.", 
        "https://agenfor.com.ar/wp-content/uploads/2019/06/Formosa-4.jpg", 
        "https://www.youtube.com/watch?v=OFnMTGlvHBg"
    ),
    (
        "Catamarca",
        "La provincia de Catamarca forma parte de la región del Noroeste argentino. Sus paisajes incluyen desde valles y ciudades, hasta una importante presencia de cerros y volcanes que la hacen un destino ideal para la práctica del montañismo y la escalada deportiva. Villas veraniegas como El Rodeo, ciudades increíbles como Belén, Tinogasta y Londres, o la belleza indescriptible de las aguas curativas de Fiambalá, cerca de Antofagasta de la Sierra, y la popularidad que ha adquirido la ya famosa Fiesta Nacional del Poncho, han hecho de Catamarca un sitio perfecto para toda la familia. La provincia ostenta entre sus atractivos naturales a varias montañas que forman la ruta de los Seismiles, todos picos de más de 6000 metros de altura con nieves eternas. A estos se suman lagunas de altura y los volcanes más elevados del mundo, los que año a año suman adeptos que quieren llegar a sus cumbres. Las festividades religiosas, entre las que se destaca la de la Virgen del Valle en la capital San Fernando del Valle de Catamarca, convocan a multitudes que llegadas de todos los puntos de la provincia se encuentran para mantener intacta su fe.", 
        "https://i.pinimg.com/originals/b8/91/d3/b891d3210f0636da935b35109953e042.jpg", 
        "https://www.youtube.com/watch?v=jDIF8A0snbk"
    ),
    (
        "La Rioja",
        "La provincia de La Rioja presenta paisajes de ensueño junto a la Cordillera de los Andes, resultando ideal para satisfacer a los amantes del turismo aventura y las actividades al aire libre. A su tradición bodeguera se ha sumado en las últimas décadas la producción de aceite de oliva, logrando que pequeños emprendimientos familiares diseminados por toda la provincia se conviertan en un atractivo en sí mismos. Además de su ciudad capital, La Rioja cuenta con otras dos localidades emblemáticas para el turismo: Chilecito y Villa Unión. Entre las tres conquistan a todos aquellos que se acercan atraídos por la belleza natural de su geografía y por las alternativas culturales de estas poblaciones. La pequeña Famatina es una de las ciudades más vanguardistas de la Rioja. Conocida por su historia minera, que hoy permanece abierta al turismo a través de La Mexicana, sus altos cerros convocan a todos los seguidores de los deportes aéreos, siendo el parapente y el aladeltismo los dos más practicados. La Fiesta de la Chaya Riojana es un evento nacional de convocatoria creciente en el cual se presentan artistas locales e internacionales, y en la que miles de turistas quieren formar parte de los festejos donde la harina se encarga de blanquear a todos los presentes. Historia, paisajes, gente y mucho color hacen de esta provincia una de las imperdibles de nuestra Argentina.", 
        "https://images.clarin.com/2015/12/11/rk89lKeVg_1256x620.jpg", 
        "https://www.youtube.com/watch?v=yjirwcgAWkI"
    ),
    (
        "Santiago del Estero",
        "La provincia de Santiago del Estero se ubica en el corazón del noroeste argentino y posee uno de los embalses más importantes y bellos de la región: el Dique Frontal Termas de Río Hondo. Meca del turismo termal y de las aguas curativas, la ciudad de Termas de Río Hondo recibe a turistas de toda la Argentina y del mundo, que se hospedan en alguno de los hoteles que, a la vera del dique o del mismo río, proporcionan salud en piletas públicas o en las bañeras de las habitaciones privadas. Santiago del Estero cuenta, además de con su capital provincial, con otros destinos turísticos que logran que el visitante prolongue su estadía para disfrutar de su antigua arquitectura, de costumbres centenarias y de otros atributos que sólo se dan en esta región del país. Las empanadas santiagueñas son parte de las tradiciones de sus habitantes, y las recetas para preparar las mismas son de lo más variadas. Lo mismo ocurre con los pastelitos, el dulce de cayote y las típicas tortillas que se ofrecen en la calle y que endulzan y conquistan a cualquier transeúnte. Entre las festividades más importantes de Santiago se encuentra la Fiesta de la Tradición en Añatuya y el Festival Selva Portal del NOA, eventos que atraen a los pobladores de toda la región. Encontrándose de paso para los que viajan a Salta o Jujuy, Santiago del Estero es famosa por sus artesanías y por la elaboración y el tejido de su cestería, lo que se manifiesta en la innumerable cantidad de ferias y puestos de artesanos a lo largo de todas las rutas provinciales, aún en los lugares menos pensados.", 
        "https://px.cdn.lanueva.com/052019/1559230138012.jpg", 
        "https://www.youtube.com/watch?v=B5M5dxcXjFE"
    ),
]

## Ejecutar la inserción de datos, el many es porque son muchos datos
cursor.executemany(query, values)

## Confirmamos la insersión
db.commit()

#Mostrar cuentas filas se crearon
print(cursor.rowcount, "records inserted")